version: "3.8"
services:
    focalboard:
        image: mattermost/focalboard
        container_name: forcalboard
        user: root
        labels:
          - "traefik.enable=true"
          - "traefik.http.routers.forcalboard.rule=Host(`board.${DOMAIN}`)"
          - "traefik.http.routers.forcalboard.entrypoints=websecure"
          - "traefik.http.routers.forcalboard.tls.certresolver=myresolver"
        volumes:
          - ./workspace:/data
        restart: unless-stopped
        networks:
          - traefik

networks:
  traefik:
    external: true
